namespace AppointmentScheduler.Domain.Entities;

public enum Permission : uint
{
    SystemPrivilege = 0,
    ReadRole,
    CreateRole,
    UpdateRole,
    DeleteRole,
    ReadUser,
    CreateUser,
    UpdateUser,
    DeleteUser,
    ReadProfile,
    CreateProfile,
    UpdateProfile,
    DeleteProfile,
    ReadDiagnosticService,
    CreateDiagnosticService,
    UpdateDiagnosticService,
    DeleteDiagnosticService,
    CreateExaminationDiagnostic,
    SealExaminationDiagnostic,
    DeleteExaminationDiagnostic,
    ReadAppointment,
    CreateAppointment,
    DeleteAppointment,
    ReadExamination,
    CreateExamination,
    UpdateExamination,
    DeleteExamination,
    ReadPrescription,
    CreatePrescription,
    SealPrescription,
    DeletePrescription
}
